backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

# media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
media_folder: "/post-images" # The src attribute for uploaded media will begin with /images/uploads

# This line should *not* be indented
publish_mode: editorial_workflow

collections:
  - name: 'post/{{slug}}/' # Used in routes, e.g., /admin/collections/blog
    label: 'Post' # Used in the UI
    folder: '/post/{{slug}}' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
